.TH "TODOPRO STATS WEEK" "1" "2026-02-27" "1.0.0" "todopro stats week Manual"
.SH NAME
todopro\-stats\-week \- Show weekly focus report (last 7 days).
.SH SYNOPSIS
.B todopro stats week
[OPTIONS]
.SH DESCRIPTION
Show weekly focus report (last 7 days).
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format (json)
