.TH "TODOPRO CONFIG DELETE-CONTEXT" "1" "2026-02-27" "1.0.0" "todopro config delete-context Manual"
.SH NAME
todopro\-config\-delete-context \- Delete a context.
.SH SYNOPSIS
.B todopro config delete-context
[OPTIONS] NAME
.SH DESCRIPTION
Delete a context.
.SH OPTIONS
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
