.TH "TODOPRO IMPORT" "1" "2026-02-27" "1.0.0" "todopro import Manual"
.SH NAME
todopro\-import \- Import data — Todoist, JSON, …
.SH SYNOPSIS
.B todopro import
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Import data — Todoist, JSON, …
.SH COMMANDS
.PP
\fBdata\fP
  Import data from JSON file.
  See \fBtodopro import-data(1)\fP for full documentation on the \fBdata\fP command.
.PP
\fBtodoist\fP
  Import tasks, projects, and labels from...
  See \fBtodopro import-todoist(1)\fP for full documentation on the \fBtodoist\fP command.
