.TH "TODOPRO LABEL LIST" "1" "2026-02-27" "1.0.0" "todopro label list Manual"
.SH NAME
todopro\-label\-list \- List all labels.
.SH SYNOPSIS
.B todopro label list
[OPTIONS]
.SH DESCRIPTION
List all labels.
.SH OPTIONS
.TP
\fB\-\-search\fP TEXT
Search labels
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: pretty]
.TP
\fB\-\-json\fP
Output as JSON (alias for --output json)
.TP
\fB\-\-compact\fP
Compact output
