.TH "TODOPRO TASK CREATE" "1" "2026-02-27" "1.0.0" "todopro task create Manual"
.SH NAME
todopro\-task\-create \- Create a new task.
.SH SYNOPSIS
.B todopro task create
[OPTIONS] CONTENT
.SH DESCRIPTION
Create a new task.
.SH OPTIONS
.TP
\fB\-\-description\fP TEXT
Description
.TP
\fB\-\-project\fP TEXT
Project ID
.TP
\fB\-\-due\fP TEXT
Due date
.TP
\fB\-\-priority\fP INTEGER
Priority (1-4)
.TP
\fB\-\-labels\fP TEXT
Comma-separated labels
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
