.TH "TODOPRO IMPORT DATA" "1" "2026-02-27" "1.0.0" "todopro import data Manual"
.SH NAME
todopro\-import\-data \- Import data from JSON file.
.SH SYNOPSIS
.B todopro import data
[OPTIONS] INPUT_FILE
.SH DESCRIPTION
Import data from JSON file.
.SH OPTIONS
.TP
\fB\-\-merge\fP
Merge with existing data
