.TH "TODOPRO FOCUS CYCLE" "1" "2026-02-27" "1.0.0" "todopro focus cycle Manual"
.SH NAME
todopro\-focus\-cycle \- Start an automatic Pomodoro cycle with...
.SH SYNOPSIS
.B todopro focus cycle
[OPTIONS] [TASK_ID]
.SH DESCRIPTION
Start an automatic Pomodoro cycle with breaks.
.SH OPTIONS
.TP
\fB\-w,\fP \-\-work INTEGER
Work duration (minutes)  [default: 25]
.TP
\fB\-s,\fP \-\-short\-break INTEGER
Short break duration (minutes)  [default: 5]
.TP
\fB\-l,\fP \-\-long\-break INTEGER
Long break duration (minutes)  [default: 15]
.TP
\fB\-c,\fP \-\-cycles INTEGER
Cycles before long break  [default: 4]
