.TH "TODOPRO PROJECT UPDATE" "1" "2026-02-27" "1.0.0" "todopro project update Manual"
.SH NAME
todopro\-project\-update \- Update a project.
.SH SYNOPSIS
.B todopro project update
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Update a project.
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Project name
.TP
\fB\-\-color\fP TEXT
Project color
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
