.TH "TODOPRO CALENDAR SET" "1" "2026-02-27" "1.0.0" "todopro calendar set Manual"
.SH NAME
todopro\-calendar\-set \- Set Google Calendar configuration (e.g.,...
.SH SYNOPSIS
.B todopro calendar set
[OPTIONS] RESOURCE CALENDAR_ID
.SH DESCRIPTION
Set Google Calendar configuration (e.g., default calendar).
