.TH "TODOPRO CALENDAR PUSH" "1" "2026-02-27" "1.0.0" "todopro calendar push Manual"
.SH NAME
todopro\-calendar\-push \- Push tasks with due dates to Google Calendar.
.SH SYNOPSIS
.B todopro calendar push
[OPTIONS]
.SH DESCRIPTION
Push tasks with due dates to Google Calendar.
.SH OPTIONS
.TP
\fB\-\-project\fP TEXT
Project ID to push
.TP
\fB\-\-label\fP TEXT
Label to filter tasks
