.TH "TODOPRO SYNC" "1" "2026-02-27" "1.0.0" "todopro sync Manual"
.SH NAME
todopro\-sync \- Sync — push, pull, status
.SH SYNOPSIS
.B todopro sync
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Sync — push, pull, status
.SH COMMANDS
.PP
\fBpull\fP
  Pull data from remote to local storage.
  See \fBtodopro sync-pull(1)\fP for full documentation on the \fBpull\fP command.
.PP
\fBpush\fP
  Push data from local to remote storage.
  See \fBtodopro sync-push(1)\fP for full documentation on the \fBpush\fP command.
.PP
\fBstatus\fP
  Show sync status for current context.
  See \fBtodopro sync-status(1)\fP for full documentation on the \fBstatus\fP command.
