.TH "TODOPRO FOCUS START" "1" "2026-02-27" "1.0.0" "todopro focus start Manual"
.SH NAME
todopro\-focus\-start \- Start a focus session on a task.
.SH SYNOPSIS
.B todopro focus start
[OPTIONS] TASK_ID
.SH DESCRIPTION
Start a focus session on a task.
.SH OPTIONS
.TP
\fB\-d,\fP \-\-duration INTEGER
Duration in minutes  [default: 25]
.TP
\fB\-t,\fP \-\-template TEXT
Use a template (deep_work, standard, quick_task)
