.TH "TODOPRO PROJECT SHARE COLLABORATORS" "1" "2026-02-27" "1.0.0" "todopro project share collaborators Manual"
.SH NAME
todopro\-project\-share\-collaborators \- List all collaborators for a project.
.SH SYNOPSIS
.B todopro project share collaborators
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
List all collaborators for a project.
