.TH "TODOPRO AUTH SIGNUP" "1" "2026-02-27" "1.0.0" "todopro auth signup Manual"
.SH NAME
todopro\-auth\-signup \- Register a new user account.
.SH SYNOPSIS
.B todopro auth signup
[OPTIONS]
.SH DESCRIPTION
Register a new user account.
.SH OPTIONS
.TP
\fB\-\-email\fP TEXT
Email address
.TP
\fB\-\-password\fP TEXT
Password
