.TH "TODOPRO SECTION UPDATE" "1" "2026-02-27" "1.0.0" "todopro section update Manual"
.SH NAME
todopro\-section\-update \- Update a section.
.SH SYNOPSIS
.B todopro section update
[OPTIONS] PROJECT_ID SECTION_ID
.SH DESCRIPTION
Update a section.
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
New section name
.TP
\fB\-\-order\fP INTEGER
New display order position
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
