.TH "TODOPRO STATS QUALITY" "1" "2026-02-27" "1.0.0" "todopro stats quality Manual"
.SH NAME
todopro\-stats\-quality \- Show focus quality metrics.
.SH SYNOPSIS
.B todopro stats quality
[OPTIONS]
.SH DESCRIPTION
Show focus quality metrics.
.SH OPTIONS
.TP
\fB\-\-days\fP INTEGER
Number of days to analyze  [default: 7]
.TP
\fB\-o,\fP \-\-output TEXT
Output format (json)
