.TH "TODOPRO TASK COMMENT DELETE" "1" "2026-02-27" "1.0.0" "todopro task comment delete Manual"
.SH NAME
todopro\-task\-comment\-delete \- Delete a comment from a task.
.SH SYNOPSIS
.B todopro task comment delete
[OPTIONS] TASK_ID COMMENT_ID
.SH DESCRIPTION
Delete a comment from a task.
.SH OPTIONS
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
