.TH "TODOPRO FOCUS TEMPLATE" "1" "2026-02-27" "1.0.0" "todopro focus template Manual"
.SH NAME
todopro\-focus\-template \- Create or delete a custom focus template.
.SH SYNOPSIS
.B todopro focus template
[OPTIONS] ACTION NAME
.SH DESCRIPTION
Create or delete a custom focus template.
.SH OPTIONS
.TP
\fB\-d,\fP \-\-duration INTEGER
Duration in minutes  [default: 25]
.TP
\fB\-\-no\-breaks\fP
Disable breaks
.TP
\fB\-\-description\fP TEXT
Template description
