.TH "TODOPRO CONTEXT LIST" "1" "2026-02-27" "1.0.0" "todopro context list Manual"
.SH NAME
todopro\-context\-list \- List all available contexts
.SH SYNOPSIS
.B todopro context list
[OPTIONS]
.SH DESCRIPTION
List all available contexts
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format: table or json  [default: table]
