.TH "TODOPRO PROJECT SHARE LEAVE" "1" "2026-02-27" "1.0.0" "todopro project share leave Manual"
.SH NAME
todopro\-project\-share\-leave \- Leave a shared project.
.SH SYNOPSIS
.B todopro project share leave
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Leave a shared project.
.SH OPTIONS
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
