.TH "TODOPRO LABEL CREATE" "1" "2026-02-27" "1.0.0" "todopro label create Manual"
.SH NAME
todopro\-label\-create \- Create a new label.
.SH SYNOPSIS
.B todopro label create
[OPTIONS] NAME
.SH DESCRIPTION
Create a new label.
.SH OPTIONS
.TP
\fB\-\-color\fP TEXT
Label color
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
