.TH "TODOPRO TASK REOPEN" "1" "2026-02-27" "1.0.0" "todopro task reopen Manual"
.SH NAME
todopro\-task\-reopen \- Reopen a completed task.
.SH SYNOPSIS
.B todopro task reopen
[OPTIONS] TASK_ID
.SH DESCRIPTION
Reopen a completed task.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
