.TH "TODOPRO TEMPLATE APPLY" "1" "2026-02-27" "1.0.0" "todopro template apply Manual"
.SH NAME
todopro\-template\-apply \- Create a task from a template.
.SH SYNOPSIS
.B todopro template apply
[OPTIONS] NAME_OR_ID
.SH DESCRIPTION
Create a task from a template.
.SH OPTIONS
.TP
\fB\-t,\fP \-\-title TEXT
Override task title
.TP
\fB\-P,\fP \-\-project TEXT
Project ID
.TP
\fB\-D,\fP \-\-due TEXT
Due date (YYYY-MM-DD or ISO datetime)
.TP
\fB\-p,\fP \-\-priority INTEGER RANGE
Override priority (1-4)  [1<=x<=4]
