.TH "TODOPRO CONFIG CURRENT-CONTEXT" "1" "2026-02-27" "1.0.0" "todopro config current-context Manual"
.SH NAME
todopro\-config\-current-context \- Show the current context.
.SH SYNOPSIS
.B todopro config current-context
[OPTIONS]
.SH DESCRIPTION
Show the current context.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: default]
