.TH "TODOPRO SECTION GET" "1" "2026-02-27" "1.0.0" "todopro section get Manual"
.SH NAME
todopro\-section\-get \- Get a section by ID.
.SH SYNOPSIS
.B todopro section get
[OPTIONS] PROJECT_ID SECTION_ID
.SH DESCRIPTION
Get a section by ID.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
