.TH "TODOPRO STATS TODAY" "1" "2026-02-27" "1.0.0" "todopro stats today Manual"
.SH NAME
todopro\-stats\-today \- Show today's focus summary (default command).
.SH SYNOPSIS
.B todopro stats today
[OPTIONS]
.SH DESCRIPTION
Show today's focus summary (default command).
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format (json)
