.TH "TODOPRO GITHUB" "1" "2026-02-27" "1.0.0" "todopro github Manual"
.SH NAME
todopro\-github \- GitHub Issues integration
.SH SYNOPSIS
.B todopro github
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
GitHub Issues integration
.SH COMMANDS
.PP
\fBimport\fP
  Import GitHub Issues as TodoPro tasks.
  See \fBtodopro github-import(1)\fP for full documentation on the \fBimport\fP command.
.PP
\fBlist-issues\fP
  List GitHub Issues in a repository.
  See \fBtodopro github-list-issues(1)\fP for full documentation on the \fBlist-issues\fP command.
