.TH "TODOPRO STATS STREAK" "1" "2026-02-27" "1.0.0" "todopro stats streak Manual"
.SH NAME
todopro\-stats\-streak \- Show focus streak information.
.SH SYNOPSIS
.B todopro stats streak
[OPTIONS]
.SH DESCRIPTION
Show focus streak information.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format (json)
