.TH "TODOPRO DATA" "1" "2026-02-27" "1.0.0" "todopro data Manual"
.SH NAME
todopro\-data \- Data — export and import
.SH SYNOPSIS
.B todopro data
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Data — export and import
.SH COMMANDS
.PP
\fBexport\fP
  Export all your data (tasks, projects,...
  See \fBtodopro data-export(1)\fP for full documentation on the \fBexport\fP command.
.PP
\fBimport\fP
  Import data from JSON file (exported via...
  See \fBtodopro data-import(1)\fP for full documentation on the \fBimport\fP command.
.PP
\fBpurge\fP
  Delete ALL your data (tasks, projects,...
  See \fBtodopro data-purge(1)\fP for full documentation on the \fBpurge\fP command.
