.TH "TODOPRO SECTION REORDER" "1" "2026-02-27" "1.0.0" "todopro section reorder Manual"
.SH NAME
todopro\-section\-reorder \- Reorder sections within a project.
.SH SYNOPSIS
.B todopro section reorder
[OPTIONS] PROJECT_ID ORDERS...
.SH DESCRIPTION
Reorder sections within a project.
.PP
Example:
    todopro section reorder <project_id> abc123:0 def456:1 ghi789:2
