.TH "TODOPRO TASK UPDATE" "1" "2026-02-27" "1.0.0" "todopro task update Manual"
.SH NAME
todopro\-task\-update \- Update a task.
.SH SYNOPSIS
.B todopro task update
[OPTIONS] TASK_ID
.SH DESCRIPTION
Update a task.
.SH OPTIONS
.TP
\fB\-\-content\fP TEXT
Task content
.TP
\fB\-\-description\fP TEXT
Description
.TP
\fB\-\-project\fP TEXT
Project ID
.TP
\fB\-\-due\fP TEXT
Due date
.TP
\fB\-\-priority\fP INTEGER
Priority (1-4)
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
