.TH "TODOPRO PROJECT ARCHIVE" "1" "2026-02-27" "1.0.0" "todopro project archive Manual"
.SH NAME
todopro\-project\-archive \- Archive a project.
.SH SYNOPSIS
.B todopro project archive
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Archive a project.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
