.TH "TODOPRO ANALYTICS STATS" "1" "2026-02-27" "1.0.0" "todopro analytics stats Manual"
.SH NAME
todopro\-analytics\-stats \- Show productivity score and basic statistics.
.SH SYNOPSIS
.B todopro analytics stats
[OPTIONS]
.SH DESCRIPTION
Show productivity score and basic statistics.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format (table/json)  [default: table]
