.TH "TODOPRO CALENDAR PULL" "1" "2026-02-27" "1.0.0" "todopro calendar pull Manual"
.SH NAME
todopro\-calendar\-pull \- Pull Google Calendar events as tasks.
.SH SYNOPSIS
.B todopro calendar pull
[OPTIONS]
.SH DESCRIPTION
Pull Google Calendar events as tasks.
.SH OPTIONS
.TP
\fB\-\-calendar\-id\fP TEXT
Calendar ID to pull from
.TP
\fB\-\-from\fP TEXT
Start date (YYYY-MM-DD)
.TP
\fB\-\-to\fP TEXT
End date (YYYY-MM-DD)
