.TH "TODOPRO CONFIG VIEW" "1" "2026-02-27" "1.0.0" "todopro config view Manual"
.SH NAME
todopro\-config\-view \- View current configuration.
.SH SYNOPSIS
.B todopro config view
[OPTIONS]
.SH DESCRIPTION
View current configuration.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
