.TH "TODOPRO CALENDAR CONFIGURE" "1" "2026-02-27" "1.0.0" "todopro calendar configure Manual"
.SH NAME
todopro\-calendar\-configure \- Configure Google Calendar auto-sync rules.
.SH SYNOPSIS
.B todopro calendar configure
[OPTIONS]
.SH DESCRIPTION
Configure Google Calendar auto-sync rules.
.SH OPTIONS
.TP
\fB\-\-push\-on\-create\fP / \-\-no\-push\-on\-create
Push to calendar when task created
.TP
\fB\-\-push\-on\-complete\fP / \-\-no\-push\-on\-complete
Update calendar when task completed
