.TH "TODOPRO CALENDAR SYNC" "1" "2026-02-27" "1.0.0" "todopro calendar sync Manual"
.SH NAME
todopro\-calendar\-sync \- Two-way incremental sync with Google...
.SH SYNOPSIS
.B todopro calendar sync
[OPTIONS]
.SH DESCRIPTION
Two-way incremental sync with Google Calendar.
.SH OPTIONS
.TP
\fB\-\-status\fP
Show sync status instead of syncing
