.TH "TODOPRO TEMPLATE DELETE" "1" "2026-02-27" "1.0.0" "todopro template delete Manual"
.SH NAME
todopro\-template\-delete \- Delete a task template.
.SH SYNOPSIS
.B todopro template delete
[OPTIONS] NAME_OR_ID
.SH DESCRIPTION
Delete a task template.
.SH OPTIONS
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
