.TH "TODOPRO SECTION DELETE" "1" "2026-02-27" "1.0.0" "todopro section delete Manual"
.SH NAME
todopro\-section\-delete \- Delete a section (tasks in the section...
.SH SYNOPSIS
.B todopro section delete
[OPTIONS] PROJECT_ID SECTION_ID
.SH DESCRIPTION
Delete a section (tasks in the section remain in the project).
.SH OPTIONS
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
