.TH "TODOPRO ANALYTICS STREAKS" "1" "2026-02-27" "1.0.0" "todopro analytics streaks Manual"
.SH NAME
todopro\-analytics\-streaks \- Show current and longest task completion...
.SH SYNOPSIS
.B todopro analytics streaks
[OPTIONS]
.SH DESCRIPTION
Show current and longest task completion streak.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format (table/json)  [default: table]
