.TH "TODOPRO TODAY" "1" "2026-02-27" "1.0.0" "todopro today Manual"
.SH NAME
todopro\-today \- Show tasks for today (overdue + today's...
.SH SYNOPSIS
.B todopro today
[OPTIONS]
.SH DESCRIPTION
Show tasks for today (overdue + today's tasks).
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: pretty]
.TP
\fB\-\-json\fP
Output as JSON (alias for --output json)
.TP
\fB\-\-compact\fP
Compact output
