.TH "TODOPRO PROJECT CREATE" "1" "2026-02-27" "1.0.0" "todopro project create Manual"
.SH NAME
todopro\-project\-create \- Create a new project.
.SH SYNOPSIS
.B todopro project create
[OPTIONS] NAME
.SH DESCRIPTION
Create a new project.
.SH OPTIONS
.TP
\fB\-\-color\fP TEXT
Project color
.TP
\fB\-\-favorite\fP
Mark as favorite
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
