.TH "TODOPRO ACHIEVEMENTS LIST" "1" "2026-02-27" "1.0.0" "todopro achievements list Manual"
.SH NAME
todopro\-achievements\-list \- Show earned achievements and badges.
.SH SYNOPSIS
.B todopro achievements list
[OPTIONS]
.SH DESCRIPTION
Show earned achievements and badges.
.SH OPTIONS
.TP
\fB\-\-all\fP
Show all achievements including unearned
