.TH "TODOPRO LABEL UPDATE" "1" "2026-02-27" "1.0.0" "todopro label update Manual"
.SH NAME
todopro\-label\-update \- Update a label.
.SH SYNOPSIS
.B todopro label update
[OPTIONS] LABEL_ID
.SH DESCRIPTION
Update a label.
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Label name
.TP
\fB\-\-color\fP TEXT
Label color
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
