.TH "TODOPRO TASK APPLY FILTER" "1" "2026-02-27" "1.0.0" "todopro task apply filter Manual"
.SH NAME
todopro\-task\-apply\-filter \- Apply a saved filter to list matching tasks.
.SH SYNOPSIS
.B todopro task apply filter
[OPTIONS] NAME
.SH DESCRIPTION
Apply a saved filter to list matching tasks.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: pretty]
