.TH "TODOPRO ENCRYPTION RECOVER" "1" "2026-02-27" "1.0.0" "todopro encryption recover Manual"
.SH NAME
todopro\-encryption\-recover \- Recover your encryption key from recovery...
.SH SYNOPSIS
.B todopro encryption recover
[OPTIONS]
.SH DESCRIPTION
Recover your encryption key from recovery phrase.
.PP
Use this if you lost your encryption key but have your 24-word recovery phrase.
