.TH "TODOPRO TASK LINK" "1" "2026-02-27" "1.0.0" "todopro task link Manual"
.SH NAME
todopro\-task\-link \- Manage task dependencies
.SH SYNOPSIS
.B todopro task link
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage task dependencies
.SH COMMANDS
.PP
\fBadd\fP
  Link two tasks with a dependency...
  See \fBtodopro task link-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBremove\fP
  Remove a dependency from a task.
  See \fBtodopro task link-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBlist\fP
  List dependencies of a task.
  See \fBtodopro task link-list(1)\fP for full documentation on the \fBlist\fP command.
