.TH "TODOPRO SYNC STATUS" "1" "2026-02-27" "1.0.0" "todopro sync status Manual"
.SH NAME
todopro\-sync\-status \- Show sync status for current context.
.SH SYNOPSIS
.B todopro sync status
[OPTIONS]
.SH DESCRIPTION
Show sync status for current context.
.PP
Displays last sync times and pending changes.
