.TH "TODOPRO PROJECT UNARCHIVE" "1" "2026-02-27" "1.0.0" "todopro project unarchive Manual"
.SH NAME
todopro\-project\-unarchive \- Unarchive a project.
.SH SYNOPSIS
.B todopro project unarchive
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Unarchive a project.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
