.TH "TODOPRO CONFIG RESET" "1" "2026-02-27" "1.0.0" "todopro config reset Manual"
.SH NAME
todopro\-config\-reset \- Reset configuration to defaults.
.SH SYNOPSIS
.B todopro config reset
[OPTIONS] [KEY]
.SH DESCRIPTION
Reset configuration to defaults.
.SH OPTIONS
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
