.TH "TODOPRO TASK SKIP" "1" "2026-02-27" "1.0.0" "todopro task skip Manual"
.SH NAME
todopro\-task\-skip \- Skip the current instance of a recurring...
.SH SYNOPSIS
.B todopro task skip
[OPTIONS] TASK_ID
.SH DESCRIPTION
Skip the current instance of a recurring task.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
