.TH "TODOPRO TASK LINK REMOVE" "1" "2026-02-27" "1.0.0" "todopro task link remove Manual"
.SH NAME
todopro\-task\-link\-remove \- Remove a dependency from a task.
.SH SYNOPSIS
.B todopro task link remove
[OPTIONS] TASK_ID
.SH DESCRIPTION
Remove a dependency from a task.
.SH OPTIONS
.TP
\fB\-d,\fP \-\-dep TEXT
Dependency ID to remove  [required]
