.TH "TODOPRO LABEL" "1" "2026-02-27" "1.0.0" "todopro label Manual"
.SH NAME
todopro\-label \- Label operations — list, create, …
.SH SYNOPSIS
.B todopro label
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Label operations — list, create, …
.SH COMMANDS
.PP
\fBlist\fP
  List all labels.
  See \fBtodopro label-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBget\fP
  Get label details.
  See \fBtodopro label-get(1)\fP for full documentation on the \fBget\fP command.
.PP
\fBcreate\fP
  Create a new label.
  See \fBtodopro label-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBupdate\fP
  Update a label.
  See \fBtodopro label-update(1)\fP for full documentation on the \fBupdate\fP command.
.PP
\fBdelete\fP
  Delete a label.
  See \fBtodopro label-delete(1)\fP for full documentation on the \fBdelete\fP command.
