.TH "TODOPRO COMPLETE" "1" "2026-02-27" "1.0.0" "todopro complete Manual"
.SH NAME
todopro\-complete \- Mark one or more tasks as completed.
.SH SYNOPSIS
.B todopro complete
[OPTIONS] TASK_IDS...
.SH DESCRIPTION
Mark one or more tasks as completed.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
.TP
\fB\-\-json\fP
Output as JSON (alias for --output json)
.TP
\fB\-\-sync\fP
Wait for completion
