.TH "TODOPRO SECTION LIST" "1" "2026-02-27" "1.0.0" "todopro section list Manual"
.SH NAME
todopro\-section\-list \- List sections in a project.
.SH SYNOPSIS
.B todopro section list
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
List sections in a project.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: pretty]
.TP
\fB\-\-json\fP
Output as JSON (alias for --output json)
