.TH "TODOPRO TEMPLATE" "1" "2026-02-27" "1.0.0" "todopro template Manual"
.SH NAME
todopro\-template \- Task templates
.SH SYNOPSIS
.B todopro template
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Task templates
.SH COMMANDS
.PP
\fBcreate\fP
  Create a new task template.
  See \fBtodopro template-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBlist\fP
  List all task templates.
  See \fBtodopro template-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBapply\fP
  Create a task from a template.
  See \fBtodopro template-apply(1)\fP for full documentation on the \fBapply\fP command.
.PP
\fBdelete\fP
  Delete a task template.
  See \fBtodopro template-delete(1)\fP for full documentation on the \fBdelete\fP command.
