.TH "TODOPRO AUTH" "1" "2026-02-27" "1.0.0" "todopro auth Manual"
.SH NAME
todopro\-auth \- Authentication — login, logout, signup
.SH SYNOPSIS
.B todopro auth
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Authentication — login, logout, signup
.SH COMMANDS
.PP
\fBlogin\fP
  Login to TodoPro.
  See \fBtodopro auth-login(1)\fP for full documentation on the \fBlogin\fP command.
.PP
\fBlogout\fP
  Logout from TodoPro.
  See \fBtodopro auth-logout(1)\fP for full documentation on the \fBlogout\fP command.
.PP
\fBsignup\fP
  Register a new user account.
  See \fBtodopro auth-signup(1)\fP for full documentation on the \fBsignup\fP command.
