.TH "TODOPRO PROJECT VIEW" "1" "2026-02-27" "1.0.0" "todopro project view Manual"
.SH NAME
todopro\-project\-view \- View project in interactive TUI board mode.
.SH SYNOPSIS
.B todopro project view
[OPTIONS] PROJECT_CODE
.SH DESCRIPTION
View project in interactive TUI board mode.
.SH OPTIONS
.TP
\fB\-\-layout\fP TEXT
View layout (board)  [default: board]
