.TH "TODOPRO PROJECT SHARE" "1" "2026-02-27" "1.0.0" "todopro project share Manual"
.SH NAME
todopro\-project\-share \- Manage project collaboration
.SH SYNOPSIS
.B todopro project share
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage project collaboration
.SH COMMANDS
.PP
\fBshare\fP
  Share a project with another user.
  See \fBtodopro project share-share(1)\fP for full documentation on the \fBshare\fP command.
.PP
\fBcollaborators\fP
  List all collaborators for a project.
  See \fBtodopro project share-collaborators(1)\fP for full documentation on the \fBcollaborators\fP command.
.PP
\fBunshare\fP
  Remove a collaborator from a project.
  See \fBtodopro project share-unshare(1)\fP for full documentation on the \fBunshare\fP command.
.PP
\fBleave\fP
  Leave a shared project.
  See \fBtodopro project share-leave(1)\fP for full documentation on the \fBleave\fP command.
