.TH "TODOPRO PROJECT DESCRIBE" "1" "2026-02-27" "1.0.0" "todopro project describe Manual"
.SH NAME
todopro\-project\-describe \- Describe a project in detail.
.SH SYNOPSIS
.B todopro project describe
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Describe a project in detail.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
