.TH "TODOPRO TASK APPLY" "1" "2026-02-27" "1.0.0" "todopro task apply Manual"
.SH NAME
todopro\-task\-apply \- Apply saved filters
.SH SYNOPSIS
.B todopro task apply
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Apply saved filters
.SH COMMANDS
.PP
\fBfilter\fP
  Apply a saved filter to list matching tasks.
  See \fBtodopro task apply-filter(1)\fP for full documentation on the \fBfilter\fP command.
