.TH "TODOPRO PROJECT SHARE SHARE" "1" "2026-02-27" "1.0.0" "todopro project share share Manual"
.SH NAME
todopro\-project\-share\-share \- Share a project with another user.
.SH SYNOPSIS
.B todopro project share share
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Share a project with another user.
.SH OPTIONS
.TP
\fB\-e,\fP \-\-email TEXT
Email of user to share with  [required]
.TP
\fB\-p,\fP \-\-permission TEXT
Permission level: editor, viewer, admin  [default: editor]
