.TH "TODOPRO PROJECT SHARE UNSHARE" "1" "2026-02-27" "1.0.0" "todopro project share unshare Manual"
.SH NAME
todopro\-project\-share\-unshare \- Remove a collaborator from a project.
.SH SYNOPSIS
.B todopro project share unshare
[OPTIONS] PROJECT_ID
.SH DESCRIPTION
Remove a collaborator from a project.
.SH OPTIONS
.TP
\fB\-\-user\-id\fP TEXT
User ID to remove
.TP
\fB\-e,\fP \-\-email TEXT
Email of user to remove (user-id required)
