.TH "TODOPRO TASK LINK ADD" "1" "2026-02-27" "1.0.0" "todopro task link add Manual"
.SH NAME
todopro\-task\-link\-add \- Link two tasks with a dependency...
.SH SYNOPSIS
.B todopro task link add
[OPTIONS] TASK_ID
.SH DESCRIPTION
Link two tasks with a dependency relationship.
.SH OPTIONS
.TP
\fB\-\-blocks\fP TEXT
ID of a task that this task blocks
.TP
\fB\-\-blocked\-by\fP TEXT
ID of a task that blocks this task
