.TH "TODOPRO TASK NEXT" "1" "2026-02-27" "1.0.0" "todopro task next Manual"
.SH NAME
todopro\-task\-next \- Show the next most important task.
.SH SYNOPSIS
.B todopro task next
[OPTIONS]
.SH DESCRIPTION
Show the next most important task.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: pretty]
