.TH "TODOPRO CONFIG GET-CONTEXTS" "1" "2026-02-27" "1.0.0" "todopro config get-contexts Manual"
.SH NAME
todopro\-config\-get-contexts \- List all available contexts.
.SH SYNOPSIS
.B todopro config get-contexts
[OPTIONS]
.SH DESCRIPTION
List all available contexts.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
