.TH "TODOPRO CONFIG SET-CONTEXT" "1" "2026-02-27" "1.0.0" "todopro config set-context Manual"
.SH NAME
todopro\-config\-set-context \- Add or update a context.
.SH SYNOPSIS
.B todopro config set-context
[OPTIONS] NAME
.SH DESCRIPTION
Add or update a context.
.SH OPTIONS
.TP
\fB\-\-endpoint\fP TEXT
API endpoint URL  [required]
.TP
\fB\-\-description\fP TEXT
Context description
