.TH "TODOPRO PROJECT LIST" "1" "2026-02-27" "1.0.0" "todopro project list Manual"
.SH NAME
todopro\-project\-list \- List projects.
.SH SYNOPSIS
.B todopro project list
[OPTIONS]
.SH DESCRIPTION
List projects.
.SH OPTIONS
.TP
\fB\-\-archived\fP
Show archived projects
.TP
\fB\-\-favorites\fP
Show only favorites
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: pretty]
.TP
\fB\-\-json\fP
Output as JSON (alias for --output json)
.TP
\fB\-\-compact\fP
Compact output
