.TH "TODOPRO TASK START" "1" "2026-02-27" "1.0.0" "todopro task start Manual"
.SH NAME
todopro\-task\-start \- Start a Pomodoro focus session on a task.
.SH SYNOPSIS
.B todopro task start
[OPTIONS] TASK_ID
.SH DESCRIPTION
Start a Pomodoro focus session on a task.
.SH OPTIONS
.TP
\fB\-\-duration\fP INTEGER
Session duration in minutes  [default: 25]
.TP
\fB\-\-template\fP TEXT
Template name
