.TH "TODOPRO STATS PROJECT" "1" "2026-02-27" "1.0.0" "todopro stats project Manual"
.SH NAME
todopro\-stats\-project \- Show statistics for a specific project.
.SH SYNOPSIS
.B todopro stats project
[OPTIONS] CONTEXT
.SH DESCRIPTION
Show statistics for a specific project.
.SH OPTIONS
.TP
\fB\-\-days\fP INTEGER
Number of days to analyze  [default: 30]
.TP
\fB\-o,\fP \-\-output TEXT
Output format (json)
