.TH "TODOPRO CONFIG USE-CONTEXT" "1" "2026-02-27" "1.0.0" "todopro config use-context Manual"
.SH NAME
todopro\-config\-use-context \- Switch to a different context (environment).
.SH SYNOPSIS
.B todopro config use-context
[OPTIONS] CONTEXT_NAME
.SH DESCRIPTION
Switch to a different context (environment).
