.TH "TODOPRO AUTH LOGIN" "1" "2026-02-27" "1.0.0" "todopro auth login Manual"
.SH NAME
todopro\-auth\-login \- Login to TodoPro.
.SH SYNOPSIS
.B todopro auth login
[OPTIONS]
.SH DESCRIPTION
Login to TodoPro.
.SH OPTIONS
.TP
\fB\-\-email\fP TEXT
Email address
.TP
\fB\-\-password\fP TEXT
Password
.TP
\fB\-\-endpoint\fP TEXT
API endpoint URL
.TP
\fB\-\-save\-profile\fP
Save as default profile
