.TH "TODOPRO TASK RESCHEDULE" "1" "2026-02-27" "1.0.0" "todopro task reschedule Manual"
.SH NAME
todopro\-task\-reschedule \- Reschedule a task or all overdue tasks.
.SH SYNOPSIS
.B todopro task reschedule
[OPTIONS] [TARGET]
.SH DESCRIPTION
Reschedule a task or all overdue tasks.
.SH OPTIONS
.TP
\fB\-d,\fP \-\-date TEXT
New due date (today/tomorrow/YYYY-MM-DD)
.TP
\fB\-y,\fP \-\-yes
Skip confirmation
