.TH "TODOPRO STATS SHOW-TODAY" "1" "2026-02-27" "1.0.0" "todopro stats show-today Manual"
.SH NAME
todopro\-stats\-show-today \- Show today's focus summary (default command).
.SH SYNOPSIS
.B todopro stats show-today
[OPTIONS]
.SH DESCRIPTION
Show today's focus summary (default command).
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output TEXT
Output format (json)
