.TH "TODOPRO ANALYTICS EXPORT" "1" "2026-02-27" "1.0.0" "todopro analytics export Manual"
.SH NAME
todopro\-analytics\-export \- Export analytics data to file.
.SH SYNOPSIS
.B todopro analytics export
[OPTIONS]
.SH DESCRIPTION
Export analytics data to file.
.SH OPTIONS
.TP
\fB\-\-format\fP TEXT
Export format (csv/json)  [default: csv]
.TP
\fB\-\-output\fP TEXT
Output file path
