.TH "TODOPRO TASK COMMENT" "1" "2026-02-27" "1.0.0" "todopro task comment Manual"
.SH NAME
todopro\-task\-comment \- Manage task comments
.SH SYNOPSIS
.B todopro task comment
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage task comments
.SH COMMANDS
.PP
\fBadd\fP
  Add a comment to a task.
  See \fBtodopro task comment-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBlist\fP
  List all comments for a task.
  See \fBtodopro task comment-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBdelete\fP
  Delete a comment from a task.
  See \fBtodopro task comment-delete(1)\fP for full documentation on the \fBdelete\fP command.
