.TH "TODOPRO SECTION CREATE" "1" "2026-02-27" "1.0.0" "todopro section create Manual"
.SH NAME
todopro\-section\-create \- Create a new section within a project.
.SH SYNOPSIS
.B todopro section create
[OPTIONS] PROJECT_ID NAME
.SH DESCRIPTION
Create a new section within a project.
.SH OPTIONS
.TP
\fB\-\-order\fP INTEGER
Display order position  [default: 0]
.TP
\fB\-o,\fP \-\-output TEXT
Output format  [default: table]
