.TH "TODOPRO CONTEXT RM" "1" "2026-02-27" "1.0.0" "todopro context rm Manual"
.SH NAME
todopro\-context\-rm \- Delete a context (alias)
.SH SYNOPSIS
.B todopro context rm
[OPTIONS] NAME
.SH DESCRIPTION
Delete a context (alias)
.SH OPTIONS
.TP
\fB\-f,\fP \-\-force
Skip confirmation
.TP
\fB\-\-delete\-db\fP
Also delete local database file
